name: check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: placeholder
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm ci
        env:
          GITHUB_TOKEN: ${{secrets.ENG_GITHUB_TOKEN}}
      - run: npm run generate
        env:
          GITHUB_TOKEN: ${{secrets.ENG_GITHUB_TOKEN}}
          SHOPIFY_API_KEY: ${{secrets.SHOPIFY_API_KEY}}
          SHOPIFY_URL: ${{secrets.SHOPIFY_URL}}
      - run: npm run validate
